### ISSUE TITLE
show tc filter json format

### ISSUE THREAD

**Issue by denisgubin** [shemminger/iproute2#31]
Dear, Sirs!

Could you help me, please?
Well...
I use Debian 10 and iproute2 had been installed on it.
Version iproute2 is iproute2-ss190107

My problem is this: 
I can't convert tc filter show output json format  to python object.
Here it is command:

```
tc qdisc add dev eno1 ingress
tc filter add dev eno1 parent ffff: protocol all u32 match u8 0 0 action mirred egress mirror dev lo
```
Have a look:
```
~$ tc -j filter show parent ffff: dev eno1
[{
        "protocol": "all",
        "pref": 49152,
        "kind": "u32",
        "chain": 0
    },{
        "protocol": "all",
        "pref": 49152,
        "kind": "u32",
        "chain": 0,
        "options": {fh 800: ht divisor 1 }
    },{
        "protocol": "all",
        "pref": 49152,
        "kind": "u32",
        "chain": 0,
        "options": {fh 800::800 order 2048 key ht 800 bkt 0 terminal flowid ??? not_in_hw 
  match 00000000/00000000 at 0
            "actions": [{
                    "order": 1,
                    "kind": "mirred",
                    "mirred_action": "mirror",
                    "direction": "egress",
                    "to_dev": "lo",
                    "control_action": {
                        "type": "pipe"
                    },
                    "index": 1,
                    "ref": 1,
                    "bind": 1
                }]
        }
    }
]


```

And then I tried to convert that output to python object I got this

```
>>> to_python_dict = json.loads(output)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 120 (char 119)
```

May be problem when there is actions in tc filter I don't know about it.
Have a look:

```
"options": {fh 800::800 order 2048 key ht 800 bkt 0 terminal flowid ??? not_in_hw 
  match 00000000/00000000 at 0
    "actions":
```

Can you explain me?

Thanks  a lot!

**Comment by shemminger** [comment]
U32 filter does not support JSON
Iproute2 uses netdev@vger.kernel.org for development not github.
